version: '3'
services:
  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
#  express:
#    build: .
#    restart: always
#    environment:
#      MONGO_USERNAME: mongo
#      MONGO_PASSWORD: password
#      MONGO_HOST: mongodb
#    depends_on:
#      - mongodb
#    ports:
#      - "3000:3000"
