version: '3'
services:
  mongodb:
    image: mongo:6.0.5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=user-api
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
#  express:
#    build: .
#    restart: always
#    environment:
#      MONGO_USERNAME: mongo
#      MONGO_PASSWORD: password
#      MONGO_HOST: mongodb
#    depends_on:
#      - mongodb
#    ports:
#      - "3000:3000"
